version: '4.18'
name: "framework"

services:
  app:
    build:
      context: ""
      dockerfile: Docker
    container_name: framework-app
    working_dir: /var/www
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.23.4-alpine
    container_name: framework-nginx
    ports:
      - 8007:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d